# scripts/generate-changelog.ps1
# Automating generation of a premium CHANGELOG.md for the GitHub Release from git commit history

param(
    [string]$Version = "3.1.0"
)

$changelogPath = "CHANGELOG.md"

$header = @"
# Document Sharing Manager v$Version Release 🚀

Welcome to the official automated release of **Document Sharing Manager v$Version**! 

Below is the changelog detailing the exact modifications incorporated into this build since the last pipeline trigger.

## 📝 What's Changed in this Release
"@

Write-Host "Fetching git log commits to build changelog..."
# Get latest 15 commits in clean bullet format
$commits = git log -n 15 --pretty=format:"* %s (%h) - %an"

if ([string]::IsNullOrWhiteSpace($commits)) {
    $commits = "* Maintenance and optimizations.*"
}

$footer = @"

---
### 🛠️ Telemetry & Observability
- This release includes automated capacity checks and real-time DORA performance tracking.
- Interactive metrics dashboard and archived reports are updated and accessible live on GitHub Pages.

*Automated Release generated by Antigravity CI/CD Engine at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').*
"@

$fullContent = "$header`n`n$commits`n`n$footer"
$fullContent | Out-File $changelogPath -Encoding utf8 -Force
Write-Host "Generated CHANGELOG.md successfully at $changelogPath."
